/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgendaTimeRouteImport } from './routes/agenda-time'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedElencoRouteImport } from './routes/_authenticated/elenco'
import { Route as AuthenticatedEstudioRouteImport } from './routes/_authenticated/estudio'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as AuthenticatedJogosIndexRouteImport } from './routes/_authenticated/jogos.index'
import { Route as AuthenticatedJogosMatchIdRouteImport } from './routes/_authenticated/jogos.$matchId'
import { Route as AuthenticatedJogosNovoRouteImport } from './routes/_authenticated/jogos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaTimeRoute = AgendaTimeRouteImport.update({
  id: '/agenda-time',
  path: '/agenda-time',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElencoRoute = AuthenticatedElencoRouteImport.update({
  id: '/elenco',
  path: '/elenco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudioRoute = AuthenticatedEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogosIndexRoute = AuthenticatedJogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogosMatchIdRoute =
  AuthenticatedJogosMatchIdRouteImport.update({
    id: '/jogos/$matchId',
    path: '/jogos/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJogosNovoRoute = AuthenticatedJogosNovoRouteImport.update({
  id: '/jogos/novo',
  path: '/jogos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda-time': typeof AgendaTimeRoute
  '/auth': typeof AuthRoute
  '/horarios': typeof HorariosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/elenco': typeof AuthenticatedElencoRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/jogos/$matchId': typeof AuthenticatedJogosMatchIdRoute
  '/jogos/novo': typeof AuthenticatedJogosNovoRoute
  '/jogos/': typeof AuthenticatedJogosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda-time': typeof AgendaTimeRoute
  '/auth': typeof AuthRoute
  '/horarios': typeof HorariosRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/elenco': typeof AuthenticatedElencoRoute
  '/estudio': typeof AuthenticatedEstudioRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/jogos/$matchId': typeof AuthenticatedJogosMatchIdRoute
  '/jogos/novo': typeof AuthenticatedJogosNovoRoute
  '/jogos': typeof AuthenticatedJogosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agenda-time': typeof AgendaTimeRoute
  '/auth': typeof AuthRoute
  '/horarios': typeof HorariosRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/elenco': typeof AuthenticatedElencoRoute
  '/_authenticated/estudio': typeof AuthenticatedEstudioRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/_authenticated/jogos/$matchId': typeof AuthenticatedJogosMatchIdRoute
  '/_authenticated/jogos/novo': typeof AuthenticatedJogosNovoRoute
  '/_authenticated/jogos/': typeof AuthenticatedJogosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda-time'
    | '/auth'
    | '/horarios'
    | '/agenda'
    | '/elenco'
    | '/estudio'
    | '/financeiro'
    | '/visao-geral'
    | '/jogos/$matchId'
    | '/jogos/novo'
    | '/jogos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda-time'
    | '/auth'
    | '/horarios'
    | '/agenda'
    | '/elenco'
    | '/estudio'
    | '/financeiro'
    | '/visao-geral'
    | '/jogos/$matchId'
    | '/jogos/novo'
    | '/jogos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda-time'
    | '/auth'
    | '/horarios'
    | '/_authenticated/agenda'
    | '/_authenticated/elenco'
    | '/_authenticated/estudio'
    | '/_authenticated/financeiro'
    | '/_authenticated/visao-geral'
    | '/_authenticated/jogos/$matchId'
    | '/_authenticated/jogos/novo'
    | '/_authenticated/jogos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgendaTimeRoute: typeof AgendaTimeRoute
  AuthRoute: typeof AuthRoute
  HorariosRoute: typeof HorariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-time': {
      id: '/agenda-time'
      path: '/agenda-time'
      fullPath: '/agenda-time'
      preLoaderRoute: typeof AgendaTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/elenco': {
      id: '/_authenticated/elenco'
      path: '/elenco'
      fullPath: '/elenco'
      preLoaderRoute: typeof AuthenticatedElencoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudio': {
      id: '/_authenticated/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof AuthenticatedEstudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogos/': {
      id: '/_authenticated/jogos/'
      path: '/jogos'
      fullPath: '/jogos/'
      preLoaderRoute: typeof AuthenticatedJogosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogos/$matchId': {
      id: '/_authenticated/jogos/$matchId'
      path: '/jogos/$matchId'
      fullPath: '/jogos/$matchId'
      preLoaderRoute: typeof AuthenticatedJogosMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogos/novo': {
      id: '/_authenticated/jogos/novo'
      path: '/jogos/novo'
      fullPath: '/jogos/novo'
      preLoaderRoute: typeof AuthenticatedJogosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedElencoRoute: typeof AuthenticatedElencoRoute
  AuthenticatedEstudioRoute: typeof AuthenticatedEstudioRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedJogosMatchIdRoute: typeof AuthenticatedJogosMatchIdRoute
  AuthenticatedJogosNovoRoute: typeof AuthenticatedJogosNovoRoute
  AuthenticatedJogosIndexRoute: typeof AuthenticatedJogosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedElencoRoute: AuthenticatedElencoRoute,
  AuthenticatedEstudioRoute: AuthenticatedEstudioRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedJogosMatchIdRoute: AuthenticatedJogosMatchIdRoute,
  AuthenticatedJogosNovoRoute: AuthenticatedJogosNovoRoute,
  AuthenticatedJogosIndexRoute: AuthenticatedJogosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgendaTimeRoute: AgendaTimeRoute,
  AuthRoute: AuthRoute,
  HorariosRoute: HorariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
